apiVersion: v2
name: external-secrets
version: 0.2.0
dependencies:
- name: external-secrets
  repository: https://charts.external-secrets.io/
  version: 0.16.0
description: External secret management for Kubernetes
home: https://github.com/external-secrets/external-secrets
icon: https://raw.githubusercontent.com/external-secrets/external-secrets/main/assets/eso-logo-large.png
keywords:
- kubernetes-external-secrets
- secrets
kubeVersion: '>= 1.19.0-0'
maintainers:
- email: mohammadsrahman@me.com
  name: mohammadsrahman
type: application
