apiVersion: v2
name: cert-manager
version: "0.0.1"
description: A Helm chart for cert-manager
home: https://cert-manager.io
icon: https://raw.githubusercontent.com/cert-manager/community/4d35a69437d21b76322157e6284be4cd64e6d2b7/logo/logo-small.png
keywords:
  - cert-manager
  - kube-lego
  - letsencrypt
  - tls
kubeVersion: '>=1.25.0-0'
maintainers:
  - name: mohammadsrahman
    email: mohammadsrahman@me.com
sources:
  - https://github.com/cert-manager/cert-manager
dependencies:
  - name: cert-manager
    version: v1.17.1
    repository: https://charts.jetstack.io
